// Hiragana characters
export const hiragana = [
  { japanese: 'あ', romaji: 'a', english: 'a', type: 'hiragana' },
  { japanese: 'い', romaji: 'i', english: 'i', type: 'hiragana' },
  { japanese: 'う', romaji: 'u', english: 'u', type: 'hiragana' },
  { japanese: 'え', romaji: 'e', english: 'e', type: 'hiragana' },
  { japanese: 'お', romaji: 'o', english: 'o', type: 'hiragana' },
  { japanese: 'か', romaji: 'ka', english: 'ka', type: 'hiragana' },
  { japanese: 'き', romaji: 'ki', english: 'ki', type: 'hiragana' },
  { japanese: 'く', romaji: 'ku', english: 'ku', type: 'hiragana' },
  { japanese: 'け', romaji: 'ke', english: 'ke', type: 'hiragana' },
  { japanese: 'こ', romaji: 'ko', english: 'ko', type: 'hiragana' },
  { japanese: 'さ', romaji: 'sa', english: 'sa', type: 'hiragana' },
  { japanese: 'し', romaji: 'shi', english: 'shi', type: 'hiragana' },
  { japanese: 'す', romaji: 'su', english: 'su', type: 'hiragana' },
  { japanese: 'せ', romaji: 'se', english: 'se', type: 'hiragana' },
  { japanese: 'そ', romaji: 'so', english: 'so', type: 'hiragana' },
  { japanese: 'た', romaji: 'ta', english: 'ta', type: 'hiragana' },
  { japanese: 'ち', romaji: 'chi', english: 'chi', type: 'hiragana' },
  { japanese: 'つ', romaji: 'tsu', english: 'tsu', type: 'hiragana' },
  { japanese: 'て', romaji: 'te', english: 'te', type: 'hiragana' },
  { japanese: 'と', romaji: 'to', english: 'to', type: 'hiragana' },
  { japanese: 'な', romaji: 'na', english: 'na', type: 'hiragana' },
  { japanese: 'に', romaji: 'ni', english: 'ni', type: 'hiragana' },
  { japanese: 'ぬ', romaji: 'nu', english: 'nu', type: 'hiragana' },
  { japanese: 'ね', romaji: 'ne', english: 'ne', type: 'hiragana' },
  { japanese: 'の', romaji: 'no', english: 'no', type: 'hiragana' },
  { japanese: 'は', romaji: 'ha', english: 'ha', type: 'hiragana' },
  { japanese: 'ひ', romaji: 'hi', english: 'hi', type: 'hiragana' },
  { japanese: 'ふ', romaji: 'fu', english: 'fu', type: 'hiragana' },
  { japanese: 'へ', romaji: 'he', english: 'he', type: 'hiragana' },
  { japanese: 'ほ', romaji: 'ho', english: 'ho', type: 'hiragana' },
  { japanese: 'ま', romaji: 'ma', english: 'ma', type: 'hiragana' },
  { japanese: 'み', romaji: 'mi', english: 'mi', type: 'hiragana' },
  { japanese: 'む', romaji: 'mu', english: 'mu', type: 'hiragana' },
  { japanese: 'め', romaji: 'me', english: 'me', type: 'hiragana' },
  { japanese: 'も', romaji: 'mo', english: 'mo', type: 'hiragana' },
  { japanese: 'や', romaji: 'ya', english: 'ya', type: 'hiragana' },
  { japanese: 'ゆ', romaji: 'yu', english: 'yu', type: 'hiragana' },
  { japanese: 'よ', romaji: 'yo', english: 'yo', type: 'hiragana' },
  { japanese: 'ら', romaji: 'ra', english: 'ra', type: 'hiragana' },
  { japanese: 'り', romaji: 'ri', english: 'ri', type: 'hiragana' },
  { japanese: 'る', romaji: 'ru', english: 'ru', type: 'hiragana' },
  { japanese: 'れ', romaji: 're', english: 're', type: 'hiragana' },
  { japanese: 'ろ', romaji: 'ro', english: 'ro', type: 'hiragana' },
  { japanese: 'わ', romaji: 'wa', english: 'wa', type: 'hiragana' },
  { japanese: 'を', romaji: 'wo', english: 'wo', type: 'hiragana' },
  { japanese: 'ん', romaji: 'n', english: 'n', type: 'hiragana' }
];

// Katakana characters
export const katakana = [
  { japanese: 'ア', romaji: 'a', english: 'a', type: 'katakana' },
  { japanese: 'イ', romaji: 'i', english: 'i', type: 'katakana' },
  { japanese: 'ウ', romaji: 'u', english: 'u', type: 'katakana' },
  { japanese: 'エ', romaji: 'e', english: 'e', type: 'katakana' },
  { japanese: 'オ', romaji: 'o', english: 'o', type: 'katakana' },
  { japanese: 'カ', romaji: 'ka', english: 'ka', type: 'katakana' },
  { japanese: 'キ', romaji: 'ki', english: 'ki', type: 'katakana' },
  { japanese: 'ク', romaji: 'ku', english: 'ku', type: 'katakana' },
  { japanese: 'ケ', romaji: 'ke', english: 'ke', type: 'katakana' },
  { japanese: 'コ', romaji: 'ko', english: 'ko', type: 'katakana' },
  { japanese: 'サ', romaji: 'sa', english: 'sa', type: 'katakana' },
  { japanese: 'シ', romaji: 'shi', english: 'shi', type: 'katakana' },
  { japanese: 'ス', romaji: 'su', english: 'su', type: 'katakana' },
  { japanese: 'セ', romaji: 'se', english: 'se', type: 'katakana' },
  { japanese: 'ソ', romaji: 'so', english: 'so', type: 'katakana' },
  { japanese: 'タ', romaji: 'ta', english: 'ta', type: 'katakana' },
  { japanese: 'チ', romaji: 'chi', english: 'chi', type: 'katakana' },
  { japanese: 'ツ', romaji: 'tsu', english: 'tsu', type: 'katakana' },
  { japanese: 'テ', romaji: 'te', english: 'te', type: 'katakana' },
  { japanese: 'ト', romaji: 'to', english: 'to', type: 'katakana' },
  { japanese: 'ナ', romaji: 'na', english: 'na', type: 'katakana' },
  { japanese: 'ニ', romaji: 'ni', english: 'ni', type: 'katakana' },
  { japanese: 'ヌ', romaji: 'nu', english: 'nu', type: 'katakana' },
  { japanese: 'ネ', romaji: 'ne', english: 'ne', type: 'katakana' },
  { japanese: 'ノ', romaji: 'no', english: 'no', type: 'katakana' },
  { japanese: 'ハ', romaji: 'ha', english: 'ha', type: 'katakana' },
  { japanese: 'ヒ', romaji: 'hi', english: 'hi', type: 'katakana' },
  { japanese: 'フ', romaji: 'fu', english: 'fu', type: 'katakana' },
  { japanese: 'ヘ', romaji: 'he', english: 'he', type: 'katakana' },
  { japanese: 'ホ', romaji: 'ho', english: 'ho', type: 'katakana' },
  { japanese: 'マ', romaji: 'ma', english: 'ma', type: 'katakana' },
  { japanese: 'ミ', romaji: 'mi', english: 'mi', type: 'katakana' },
  { japanese: 'ム', romaji: 'mu', english: 'mu', type: 'katakana' },
  { japanese: 'メ', romaji: 'me', english: 'me', type: 'katakana' },
  { japanese: 'モ', romaji: 'mo', english: 'mo', type: 'katakana' },
  { japanese: 'ヤ', romaji: 'ya', english: 'ya', type: 'katakana' },
  { japanese: 'ユ', romaji: 'yu', english: 'yu', type: 'katakana' },
  { japanese: 'ヨ', romaji: 'yo', english: 'yo', type: 'katakana' },
  { japanese: 'ラ', romaji: 'ra', english: 'ra', type: 'katakana' },
  { japanese: 'リ', romaji: 'ri', english: 'ri', type: 'katakana' },
  { japanese: 'ル', romaji: 'ru', english: 'ru', type: 'katakana' },
  { japanese: 'レ', romaji: 're', english: 're', type: 'katakana' },
  { japanese: 'ロ', romaji: 'ro', english: 'ro', type: 'katakana' },
  { japanese: 'ワ', romaji: 'wa', english: 'wa', type: 'katakana' },
  { japanese: 'ヲ', romaji: 'wo', english: 'wo', type: 'katakana' },
  { japanese: 'ン', romaji: 'n', english: 'n', type: 'katakana' }
];

// Common Japanese phrases
export const phrases = [
  { japanese: 'おはよう', romaji: 'ohayou', english: 'Good morning (casual)', type: 'phrase' },
  { japanese: 'おはようございます', romaji: 'ohayou gozaimasu', english: 'Good morning (polite)', type: 'phrase' },
  { japanese: 'こんにちは', romaji: 'konnichiwa', english: 'Hello / Good afternoon', type: 'phrase' },
  { japanese: 'こんばんは', romaji: 'konbanwa', english: 'Good evening', type: 'phrase' },
  { japanese: 'ありがとう', romaji: 'arigatou', english: 'Thank you (casual)', type: 'phrase' },
  { japanese: 'ありがとうございます', romaji: 'arigatou gozaimasu', english: 'Thank you (polite)', type: 'phrase' },
  { japanese: 'すみません', romaji: 'sumimasen', english: 'Excuse me / Sorry', type: 'phrase' },
  { japanese: 'ごめんなさい', romaji: 'gomen nasai', english: 'I\'m sorry', type: 'phrase' },
  { japanese: 'さようなら', romaji: 'sayounara', english: 'Goodbye', type: 'phrase' },
  { japanese: 'じゃあね', romaji: 'jaa ne', english: 'See you (casual)', type: 'phrase' },
  { japanese: 'はい', romaji: 'hai', english: 'Yes', type: 'phrase' },
  { japanese: 'いいえ', romaji: 'iie', english: 'No', type: 'phrase' },
  { japanese: 'お願いします', romaji: 'onegaishimasu', english: 'Please', type: 'phrase' },
  { japanese: 'どういたしまして', romaji: 'douitashimashite', english: 'You\'re welcome', type: 'phrase' },
  { japanese: 'いただきます', romaji: 'itadakimasu', english: 'Let\'s eat (before meal)', type: 'phrase' },
  { japanese: 'ごちそうさまでした', romaji: 'gochisousama deshita', english: 'Thank you for the meal (after eating)', type: 'phrase' },
  { japanese: 'はじめまして', romaji: 'hajimemashite', english: 'Nice to meet you', type: 'phrase' },
  { japanese: 'よろしくお願いします', romaji: 'yoroshiku onegaishimasu', english: 'Please treat me well', type: 'phrase' },
  { japanese: 'おやすみなさい', romaji: 'oyasuminasai', english: 'Good night', type: 'phrase' },
  { japanese: 'お元気ですか', romaji: 'ogenki desu ka', english: 'How are you?', type: 'phrase' },
  { japanese: '元気です', romaji: 'genki desu', english: 'I\'m fine', type: 'phrase' },
  { japanese: 'わかりました', romaji: 'wakarimashita', english: 'I understand', type: 'phrase' },
  { japanese: 'わかりません', romaji: 'wakarimasen', english: 'I don\'t understand', type: 'phrase' },
  { japanese: 'もう一度お願いします', romaji: 'mou ichido onegaishimasu', english: 'One more time please', type: 'phrase' },
  { japanese: '日本語がわかりません', romaji: 'nihongo ga wakarimasen', english: 'I don\'t understand Japanese', type: 'phrase' },
  { japanese: 'トイレはどこですか', romaji: 'toire wa doko desu ka', english: 'Where is the bathroom?', type: 'phrase' },
  { japanese: 'いくらですか', romaji: 'ikura desu ka', english: 'How much is it?', type: 'phrase' },
  { japanese: 'これをください', romaji: 'kore wo kudasai', english: 'I\'ll take this please', type: 'phrase' },
  { japanese: '水をください', romaji: 'mizu wo kudasai', english: 'Water please', type: 'phrase' },
  { japanese: 'お腹がすきました', romaji: 'onaka ga sukimashita', english: 'I\'m hungry', type: 'phrase' },
  { japanese: '美味しい', romaji: 'oishii', english: 'Delicious', type: 'phrase' },
  { japanese: 'お名前は', romaji: 'onamae wa', english: 'What\'s your name?', type: 'phrase' },
  { japanese: '私の名前は', romaji: 'watashi no namae wa', english: 'My name is', type: 'phrase' },
  { japanese: '大丈夫です', romaji: 'daijoubu desu', english: 'It\'s okay / I\'m fine', type: 'phrase' },
  { japanese: '助けて', romaji: 'tasukete', english: 'Help!', type: 'phrase' },
  { japanese: 'ちょっと待ってください', romaji: 'chotto matte kudasai', english: 'Please wait a moment', type: 'phrase' },
  { japanese: '行きましょう', romaji: 'ikimashou', english: 'Let\'s go', type: 'phrase' },
  { japanese: '帰ります', romaji: 'kaerimasu', english: 'I\'m going home', type: 'phrase' },
  { japanese: 'お疲れ様でした', romaji: 'otsukaresama deshita', english: 'Good work (after work)', type: 'phrase' },
  { japanese: '頑張って', romaji: 'ganbatte', english: 'Good luck / Do your best', type: 'phrase' }
];

// Combine all data
export const allData = [...hiragana, ...katakana, ...phrases];
